#!/bin/bash
set -eux

IMAGE_PREFIX=${IMAGE_PREFIX:-minimalcompact}

echo "--> BUILDING ${IMAGE_PREFIX}/python-boost"
docker build --pull -f python-boost/Dockerfile -t "${IMAGE_PREFIX}/python-boost" python-boost/

echo "--> BUILDING ${IMAGE_PREFIX}/thumbor"
docker build --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" -f thumbor/Dockerfile -t "${IMAGE_PREFIX}/thumbor" thumbor/
# introspecting version by running the built image
THUMBOR_VERSION=$(docker run --rm "${IMAGE_PREFIX}/thumbor" bash -c "pip freeze |grep ^thumbor== | cut -d= -f 3")
echo "THUMBOR VERSION: ${THUMBOR_VERSION}"

echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/thumbor" "${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:latest"
docker tag "${IMAGE_PREFIX}/thumbor" "${IMAGE_PREFIX}/thumbor:latest"

echo "--> BUILDING ${IMAGE_PREFIX}/thumbor:simd-sse4"
docker build --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" --build-arg SIMD_LEVEL=sse4 -f thumbor/Dockerfile -t "${IMAGE_PREFIX}/thumbor-simd-sse4" thumbor/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-sse4"
docker tag "${IMAGE_PREFIX}/thumbor-simd-sse4" "${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-sse4"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:latest-simd-sse4"
docker tag "${IMAGE_PREFIX}/thumbor-simd-sse4" "${IMAGE_PREFIX}/thumbor:latest-simd-sse4"

echo "--> BUILDING ${IMAGE_PREFIX}/thumbor:simd-avx2"
docker build --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" --build-arg SIMD_LEVEL=avx2  -f thumbor/Dockerfile -t "${IMAGE_PREFIX}/thumbor-simd-avx2" thumbor/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-avx2"
docker tag "${IMAGE_PREFIX}/thumbor-simd-avx2" "${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-avx2"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:latest-simd-avx2"
docker tag "${IMAGE_PREFIX}/thumbor-simd-avx2" "${IMAGE_PREFIX}/thumbor:latest-simd-avx2"

echo "--> BUILDING ${IMAGE_PREFIX}/thumbor-nginx-proxy (DEPRECATED)"
docker build --pull -f nginx-proxy/Dockerfile -t "${IMAGE_PREFIX}/thumbor-nginx-proxy" nginx-proxy/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy" "${IMAGE_PREFIX}/thumbor-nginx-proxy:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy:latest"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy" "${IMAGE_PREFIX}/thumbor-nginx-proxy:latest"

echo "--> BUILDING ${IMAGE_PREFIX}/thumbor-nginx-proxy-cache"
docker build --pull -f nginx-proxy-cache/Dockerfile -t "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" nginx-proxy-cache/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:latest"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:latest"

echo "--> BUILDING ${IMAGE_PREFIX}/remotecv"
docker build --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" --build-arg THUMBOR_TAG=latest -f remotecv/Dockerfile -t "${IMAGE_PREFIX}/remotecv" remotecv/
echo "--> TAGGING ${IMAGE_PREFIX}/remotecv:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/remotecv" "${IMAGE_PREFIX}/remotecv:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/remotecv:latest"
docker tag "${IMAGE_PREFIX}/remotecv" "${IMAGE_PREFIX}/remotecv:latest"
