#!/bin/bash
set -eu

IMAGE_PREFIX=${IMAGE_PREFIX:-minimalcompact}

@build() {
    local -a -r args=( "$@" )
    local -r args_len="${#args[@]}"
    local -r image="${args[$((args_len - 2))]}"
    echo "--> PULLING $image"
    docker pull "$image" || true

    echo "--> BUILDING $image"
    docker build --cache-from "$image" "${args[@]}"
}

@build --pull -f python-boost/Dockerfile -t "${IMAGE_PREFIX}/python-boost" python-boost/

@build --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" -f thumbor/Dockerfile -t "${IMAGE_PREFIX}/thumbor" thumbor/

# introspecting version by running the built image
THUMBOR_VERSION=$(docker run --rm "${IMAGE_PREFIX}/thumbor" bash -c "python -c 'import thumbor; print(thumbor.__version__)'")
echo "THUMBOR VERSION: ${THUMBOR_VERSION}"

echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/thumbor" "${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:latest"
docker tag "${IMAGE_PREFIX}/thumbor" "${IMAGE_PREFIX}/thumbor:latest"

@build --cache-from "${IMAGE_PREFIX}/thumbor" --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" --build-arg SIMD_LEVEL=sse4 -f thumbor/Dockerfile -t "${IMAGE_PREFIX}/thumbor-simd-sse4" thumbor/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-sse4"
docker tag "${IMAGE_PREFIX}/thumbor-simd-sse4" "${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-sse4"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:latest-simd-sse4"
docker tag "${IMAGE_PREFIX}/thumbor-simd-sse4" "${IMAGE_PREFIX}/thumbor:latest-simd-sse4"

@build --cache-from "${IMAGE_PREFIX}/thumbor" --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" --build-arg SIMD_LEVEL=avx2  -f thumbor/Dockerfile -t "${IMAGE_PREFIX}/thumbor-simd-avx2" thumbor/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-avx2"
docker tag "${IMAGE_PREFIX}/thumbor-simd-avx2" "${IMAGE_PREFIX}/thumbor:${THUMBOR_VERSION}-simd-avx2"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor:latest-simd-avx2"
docker tag "${IMAGE_PREFIX}/thumbor-simd-avx2" "${IMAGE_PREFIX}/thumbor:latest-simd-avx2"

@build --pull -f nginx-proxy/Dockerfile -t "${IMAGE_PREFIX}/thumbor-nginx-proxy" nginx-proxy/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy" "${IMAGE_PREFIX}/thumbor-nginx-proxy:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy:latest"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy" "${IMAGE_PREFIX}/thumbor-nginx-proxy:latest"

@build --pull -f nginx-proxy-cache/Dockerfile -t "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" nginx-proxy-cache/
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:latest"
docker tag "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache:latest"

@build --build-arg "IMAGE_PREFIX=${IMAGE_PREFIX}" --build-arg THUMBOR_TAG=latest -f remotecv/Dockerfile -t "${IMAGE_PREFIX}/remotecv" remotecv/
echo "--> TAGGING ${IMAGE_PREFIX}/remotecv:${THUMBOR_VERSION}"
docker tag "${IMAGE_PREFIX}/remotecv" "${IMAGE_PREFIX}/remotecv:${THUMBOR_VERSION}"
echo "--> TAGGING ${IMAGE_PREFIX}/remotecv:latest"
docker tag "${IMAGE_PREFIX}/remotecv" "${IMAGE_PREFIX}/remotecv:latest"
