#!/bin/bash

set -eux

IMAGE_PREFIX=${IMAGE_PREFIX:-minimalcompact}

BRANCH=$1
# introspecting version by running the built image
THUMBOR_VERSION=$(docker run --rm "${IMAGE_PREFIX}/thumbor" bash -c "python -c 'import thumbor; print(thumbor.__version__)'")
echo "THUMBOR VERSION: ${THUMBOR_VERSION}"

@push() {
    local -r img=$1 tag=${2:-} latest=${3:-latest}
    if [ "$tag" ]; then
        echo "--> PUSHING $img:$tag"
        docker push "$img:$tag"
    fi
    if [ "$BRANCH" == "master" ]; then
        echo "--> PUSHING $img:$latest"
        docker push "$img:$latest"
    fi
}

@push "${IMAGE_PREFIX}/python-boost"
@push "${IMAGE_PREFIX}/thumbor-simd-sse4"
@push "${IMAGE_PREFIX}/thumbor-simd-avx2"
@push "${IMAGE_PREFIX}/thumbor-nginx-proxy" "${THUMBOR_VERSION}"
@push "${IMAGE_PREFIX}/thumbor-nginx-proxy-cache" "${THUMBOR_VERSION}"
@push "${IMAGE_PREFIX}/thumbor" "${THUMBOR_VERSION}"
@push "${IMAGE_PREFIX}/thumbor" "${THUMBOR_VERSION}-simd-sse4" latest-simd-sse4
@push "${IMAGE_PREFIX}/thumbor" "${THUMBOR_VERSION}-simd-avx2" latest-simd-avx2
